import { useState } from "react";
import Page from "../components/Page";
import Card from "../components/Card";
import SectionTitle from "../components/SectionTitle";
import EditFormSheet from "../components/EditFormSheet";
import EmptyState from "../components/EmptyState";
import { PlaneTakeoff, Luggage, Pencil, PlusCircle } from "lucide-react";

function BoardingCard({flight,label,onEdit,onClear}){const has=Boolean(flight.flightNumber||flight.airline);if(!has)return <Card className="empty-state-card"><EmptyState icon={PlaneTakeoff} title={`No ${label.toLowerCase()} flight yet`} description="Add the airline, route, dates, times and baggage allowance." actionLabel={`Add ${label} Flight`} onAction={onEdit}/></Card>;return <Card className="boarding-pass-v2 boarding-pass-v5 flight-leg-card"><div className="pass-top"><div><span className="eyebrow">{label} · {flight.airline||"Airline"}</span><h2>{flight.flightNumber||"Flight"}</h2></div><PlaneTakeoff size={34}/></div><div className="pass-date">{flight.departureDate||"Date not set"} · {flight.departureTime||"Time not set"}</div><div className="pass-route"><div><strong>{flight.departureCode||"FROM"}</strong><span>{flight.departureTime}</span><p>{flight.departureAirport}</p></div><div className="route-line"><span>✈</span></div><div><strong>{flight.arrivalCode||"TO"}</strong><span>{flight.arrivalTime}</span><p>{flight.arrivalAirport}</p></div></div><div className="pass-details pass-details-v5"><div><small>Terminal</small><strong>{flight.terminal||"—"}</strong></div><div><small>Gate</small><strong>{flight.gate||"—"}</strong></div><div><small>Carry-on</small><strong>{flight.carryOn||"—"}</strong></div><div><small>Checked</small><strong>{flight.checked||"—"}</strong></div></div><div className="card-action-row"><button className="hero-action" onClick={onEdit}><Pencil size={15}/> Edit {label}</button><button className="secondary-button" onClick={onClear}>Remove</button></div></Card>}

export default function Flight({store}){const {trip,updateFlightField,updateReturnFlightField,clearFlight}=store;const [editing,setEditing]=useState(null);const outboundFields=["airline","flightNumber","departureCode","arrivalCode","departureAirport","arrivalAirport","departureDate","departureTime","arrivalDate","arrivalTime","terminal","gate","seat","carryOn","checked"];const returnFields=[...outboundFields,"airportTargetTime","leaveByTime","leaveFrom"];const flight=editing==="return"?trip.returnFlight:trip.flight;const updater=editing==="return"?updateReturnFlightField:updateFlightField;const fields=editing==="return"?returnFields:outboundFields;const save=draft=>fields.forEach(key=>updater(key,draft[key]));return <Page><header className="app-header"><div><span className="eyebrow">Travel Itinerary</span><h1>Flight</h1></div><span className="status-chip">{trip.flight.flightNumber?"Saved":"Planning"}</span></header><BoardingCard flight={trip.flight} label="Outbound" onEdit={()=>setEditing("outbound")} onClear={()=>confirm("Remove outbound flight details?")&&clearFlight("outbound")}/><BoardingCard flight={trip.returnFlight} label="Return" onEdit={()=>setEditing("return")} onClear={()=>confirm("Remove return flight details?")&&clearFlight("return")}/><SectionTitle title="Flight Notes" subtitle="Keep the details you need on travel day."/><Card className="timeline-item"><Luggage/><div><strong>Baggage allowances</strong><p>Save cabin and checked-baggage limits for each direction so they are easy to check later.</p></div></Card><EditFormSheet title={`${editing==="return"?"Edit Return":"Edit Outbound"} Flight`} open={Boolean(editing)} values={flight} fields={fields} onSave={save} onClose={()=>setEditing(null)}/></Page>}
