import { useState } from "react";
import Page from "../components/Page";
import Card from "../components/Card";
import SectionTitle from "../components/SectionTitle";
import EditFormSheet from "../components/EditFormSheet";
import EmptyState from "../components/EmptyState";
import { MapPin, Copy, Train, Hotel as HotelIcon, Pencil, BadgeDollarSign } from "lucide-react";

export default function Hotel({store}){const {trip,updateHotelField,clearHotel}=store;const [open,setOpen]=useState(false);const h=trip.hotel;const has=Boolean(h.name);const fields=["name","status","rating","area","room","addressEnglish","addressKorean","checkInDate","checkOutDate","checkInTime","checkOutTime","nearestStation","stationWalk","paidPriceSGD","cancellation"];const copyAddress=async()=>{const text=[h.name,h.addressKorean,h.addressEnglish].filter(Boolean).join("\n");try{await navigator.clipboard.writeText(text);window.ftosToast?.("Hotel address copied");}catch{window.ftosToast?.("Copy unavailable","warning");}};const save=draft=>fields.forEach(key=>updateHotelField(key,draft[key]));return <Page><header className="app-header"><div><span className="eyebrow">Accommodation</span><h1>Hotel</h1></div><span className="status-chip">{has?"Saved":"Planning"}</span></header>{!has?<Card className="empty-state-card"><EmptyState icon={HotelIcon} title="No hotel added yet" description="Add your accommodation, check-in dates, room, address and booking notes." actionLabel="Add Hotel" onAction={()=>setOpen(true)}/></Card>:<><Card className="hotel-card-v2 hotel-card-v5"><div className="hotel-photo"><HotelIcon size={42}/></div><div className="hotel-info"><span className="eyebrow">{h.area||"Accommodation"}</span><h2>{h.name}</h2><p>{[h.rating,`${h.checkInDate} → ${h.checkOutDate}`].filter(Boolean).join(" · ")}</p>{h.paidPriceSGD&&<span className="price-pill"><BadgeDollarSign size={15}/> {trip.homeCurrency||"SGD"} {Number(h.paidPriceSGD).toFixed(2)} paid</span>}<span className="booking-confirmed-chip">{h.status}</span><div className="card-action-row"><button className="edit-pill" onClick={()=>setOpen(true)}><Pencil size={15}/> Edit Hotel</button><button className="secondary-button" onClick={()=>confirm("Remove hotel details?")&&clearHotel()}>Remove</button></div></div></Card>{(h.addressEnglish||h.addressKorean)&&<><SectionTitle title="Address"/><Card className="address-action"><MapPin/><div><strong>{h.addressKorean||h.addressEnglish}</strong><p>{h.addressEnglish}</p></div><button onClick={copyAddress}><Copy size={15}/> Copy</button></Card></>}{h.nearestStation&&<Card className="timeline-item"><Train/><div><strong>Nearest transport</strong><p>{h.nearestStation}{h.stationWalk?` · ${h.stationWalk}`:""}</p></div></Card>}{h.cancellation&&<Card className="timeline-item"><BadgeDollarSign/><div><strong>Booking notes</strong><p>{h.cancellation}</p></div></Card>}</>}<EditFormSheet title="Edit Hotel Details" open={open} values={h} fields={fields} onSave={save} onClose={()=>setOpen(false)}/></Page>}
